[package]
name = "rslox"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[features]
debug_trace_execution = []

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }

[[example]]
name = "basic_arithmetic"

[[example]]
name = "cli"
